"""Walk 2h: Voice assignment.

Assigns voices from the ``voice_config`` table to characters in a book by
matching each character's voice profile (generated by Walk 2g and stored in
``character_metadata`` key='voice_profile') against the available voices.

For each character, the walk:
1. Reads the character's voice profile from ``character_metadata``.
2. Loads all available voices from ``voice_config``.
3. Sends the voice profile and available voices to an LLM for matching.
4. Parses the response (voice_config_id or null, reasoning, confidence).
5. Applies the confidence filter and updates ``character.voice_assignment_id``.

Confidence filter:
- ≥0.7: auto-accept (voice_assignment_id set)
- <0.5: auto-reject (voice_assignment_id stays NULL)
- 0.5–0.7: flagged for user review (voice_assignment_id set but tracked)

Voice assignment is NOT locked — users can change assignments via the frontend
by updating ``character.voice_assignment_id`` directly.

LLM configuration is resolved via ``resolve_task_llm('voice_assignment')``
with temperature=0.1 for format stability.
"""

from __future__ import annotations

import json
import logging
import re
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from app.pipeline.adapter import PipelineStorage

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def execute(book_id: str, storage: PipelineStorage, config: dict[str, Any]) -> dict:
    """Run Walk 2h voice assignment for a book.

    Queries characters for the book, reads each character's voice profile,
    loads available voices from ``voice_config``, sends them to an LLM for
    matching, parses the response, and updates ``character.voice_assignment_id``.

    Parameters
    ----------
    book_id:
        UUID of the book to process.
    storage:
        Pipeline storage adapter.
    config:
        App config dict (passed to ``resolve_task_llm``).

    Returns
    -------
    dict:
        Summary with keys: ``book_id``, ``characters_processed``,
        ``voices_matched``, ``voices_unmatched``, ``assignments_for_review``,
        ``errors``.
    """
    from app.utils import create_llm_client, resolve_task_llm

    result: dict[str, Any] = {
        "book_id": book_id,
        "characters_processed": 0,
        "voices_matched": 0,
        "voices_unmatched": 0,
        "assignments_for_review": 0,
        "errors": [],
    }

    # Resolve LLM config for voice assignment
    llm_config = resolve_task_llm("voice_assignment", config_path=None)
    client, _ = create_llm_client(config_path=None)
    model_name = llm_config["model_name"]
    temperature = llm_config["temperature"]
    reasoning_effort = llm_config.get("reasoning_effort")

    # Look up book existence
    book_rows = storage.execute_query(
        "SELECT series_id FROM book WHERE id = ?", (book_id,)
    )
    if not book_rows:
        logger.error(f"Book {book_id} not found")
        result["errors"].append({"book_id": book_id, "error": "Book not found"})
        return result

    # Load available voices from voice_config
    available_voices = _load_voice_config(storage)

    if not available_voices:
        logger.warning("No voices found in voice_config table — all characters will be unmatched")

    # Load existing characters for this book
    existing_characters = _load_existing_characters(book_id, storage)

    for char_row in existing_characters:
        character_id = char_row["id"]
        character_name = char_row["name"]

        result["characters_processed"] += 1

        try:
            _process_character(
                character_id=character_id,
                character_name=character_name,
                available_voices=available_voices,
                storage=storage,
                client=client,
                model_name=model_name,
                temperature=temperature,
                reasoning_effort=reasoning_effort,
                result=result,
            )
        except Exception as e:
            logger.error(f"Error processing character {character_id}: {e}")
            result["errors"].append({"character_id": character_id, "error": str(e)})

    return result


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _load_existing_characters(
    book_id: str, storage: PipelineStorage
) -> list[dict[str, Any]]:
    """Load existing character id and name for this book."""
    rows = storage.execute_query(
        """
        SELECT c.id, c.name
        FROM character c
        JOIN character_book cb ON cb.character_id = c.id
        WHERE cb.book_id = ?
        ORDER BY c.name
        """,
        (book_id,),
    )
    return [
        {
            "id": row["id"],
            "name": row["name"],
        }
        for row in rows
    ]


def _load_voice_config(storage: PipelineStorage) -> list[dict[str, str]]:
    """Load all available voices from the voice_config table.

    Returns a list of dicts with id, name, and description.
    """
    rows = storage.execute_query(
        "SELECT id, name, description FROM voice_config ORDER BY name"
    )
    return [
        {
            "id": row["id"],
            "name": row["name"] or "",
            "description": row["description"] or "",
        }
        for row in rows
    ]


def _get_voice_profile(
    character_id: str, storage: PipelineStorage
) -> dict | None:
    """Retrieve the character's voice profile from character_metadata.

    Returns the parsed voice profile dict, or None if not found.
    """
    rows = storage.execute_query(
        "SELECT value FROM character_metadata WHERE character_id = ? AND key = 'voice_profile'",
        (character_id,),
    )
    if not rows:
        return None

    value = rows[0]["value"]
    if not value:
        return None

    try:
        profile = json.loads(value)
        if isinstance(profile, dict):
            return profile
    except json.JSONDecodeError:
        logger.warning(f"Invalid voice_profile JSON for character {character_id}")

    return None


def _process_character(
    character_id: str,
    character_name: str,
    available_voices: list[dict[str, str]],
    storage: PipelineStorage,
    client: Any,
    model_name: str,
    temperature: float,
    reasoning_effort: str | None,
    result: dict,
) -> None:
    """Process a single character: read voice profile, match to available voice, assign."""
    # Read voice profile from character_metadata
    voice_profile = _get_voice_profile(character_id, storage)

    if voice_profile is None:
        logger.warning(
            f"No voice profile found for character {character_id} ({character_name}) — skipping"
        )
        result["voices_unmatched"] += 1
        return

    if not available_voices:
        logger.warning(
            f"No available voices in voice_config for character {character_id} ({character_name})"
        )
        result["voices_unmatched"] += 1
        return

    # Build LLM prompt
    prompt = _build_voice_assignment_prompt(
        character_name=character_name,
        voice_profile=voice_profile,
        available_voices=available_voices,
    )

    # Call LLM
    response_text = _call_llm(
        client=client,
        model_name=model_name,
        temperature=temperature,
        reasoning_effort=reasoning_effort,
        prompt=prompt,
    )

    # Parse response
    match_data = _parse_llm_response(response_text)

    if not match_data:
        logger.warning(f"Failed to parse voice assignment for character {character_id}")
        result["voices_unmatched"] += 1
        return

    voice_config_id = match_data.get("voice_config_id")
    confidence = match_data.get("confidence", 0.8)
    if not isinstance(confidence, (int, float)):
        confidence = 0.8
    # Clamp to [0, 1]
    confidence = max(0.0, min(1.0, float(confidence)))

    # Confidence filter
    if confidence < 0.5:
        # Auto-reject — leave voice_assignment_id NULL
        result["voices_unmatched"] += 1
        return

    is_review = 0.5 <= confidence < 0.7

    # If we have a voice match and confidence >= 0.5, assign it
    if voice_config_id is not None:
        # Validate that voice_config_id exists in available voices
        valid_ids = {v["id"] for v in available_voices}
        if voice_config_id not in valid_ids:
            logger.warning(
                f"LLM returned invalid voice_config_id '{voice_config_id}' "
                f"for character {character_id} — not in voice_config"
            )
            result["voices_unmatched"] += 1
            return

        # Update character.voice_assignment_id
        conn = storage.get_connection()
        conn.execute("SAVEPOINT walk_2h_voice_assignment")
        try:
            storage.execute_update(
                "UPDATE character SET voice_assignment_id = ? WHERE id = ?",
                (voice_config_id, character_id),
            )
            conn.execute("RELEASE SAVEPOINT walk_2h_voice_assignment")
        except Exception:
            conn.execute("ROLLBACK TO SAVEPOINT walk_2h_voice_assignment")
            raise

        result["voices_matched"] += 1

        if is_review:
            result["assignments_for_review"] += 1
    else:
        # LLM returned null voice_config_id — no match
        result["voices_unmatched"] += 1


def _build_voice_assignment_prompt(
    character_name: str,
    voice_profile: dict,
    available_voices: list[dict[str, str]],
) -> str:
    """Build the LLM prompt for voice assignment matching.

    Includes character name, voice profile, and available voices list.
    """
    voice_profile_json = json.dumps(voice_profile, indent=2)

    # Format available voices
    voice_lines = []
    for idx, voice in enumerate(available_voices, start=1):
        voice_id = voice["id"]
        voice_name = voice["name"]
        voice_desc = voice["description"] or "(no description)"
        voice_lines.append(f"  {idx}. id=\"{voice_id}\", name=\"{voice_name}\", description=\"{voice_desc}\"")

    voices_text = "\n".join(voice_lines)

    prompt = f"""You are assigning a text-to-speech voice to a character in an audiobook.

Character name: {character_name}

Character's voice profile (generated from analysis of the character's description and dialogue):
{voice_profile_json}

Available voices in the voice library:
{voices_text}

Based on the character's voice profile and the available voices, which voice (if any) is the best match?

Return a JSON object with:
- "voice_config_id": the id of the best matching voice (string), or null if no voice is a good match
- "reasoning": a brief explanation of why this voice was chosen or why no match was found
- "confidence": float between 0.0 and 1.0 indicating your confidence in this match

Return ONLY a JSON object, no other text.

Example:
{{"voice_config_id": "voice-001", "reasoning": "The warm, authoritative tone matches the character's profile.", "confidence": 0.85}}

If no voice is suitable:
{{"voice_config_id": null, "reasoning": "None of the available voices match this character's profile.", "confidence": 0.3}}
"""
    return prompt


def _call_llm(
    client: Any,
    model_name: str,
    temperature: float,
    reasoning_effort: str | None,
    prompt: str,
) -> str:
    """Call the LLM and return the response text."""
    messages = [
        {
            "role": "system",
            "content": "You are a voice casting director for audiobook production, matching characters to available text-to-speech voices.",
        },
        {"role": "user", "content": prompt},
    ]

    extra_body = {}
    if reasoning_effort is not None:
        extra_body["reasoning_effort"] = reasoning_effort

    response = client.chat.completions.create(
        model=model_name,
        messages=messages,
        temperature=temperature,
        extra_body=extra_body if extra_body else None,
    )

    return response.choices[0].message.content.strip()


def _parse_llm_response(response_text: str) -> dict:
    """Parse the LLM response into a voice assignment match dict.

    Returns a dict with voice_config_id (str or None), reasoning (str),
    and confidence (float). If parsing fails, returns empty dict.
    """
    # Try json.loads first
    try:
        match_data = json.loads(response_text)
    except json.JSONDecodeError:
        # Try to find JSON object in response with regex fallback
        match = re.search(r"\{[\s\S]*\}", response_text)
        if match:
            try:
                match_data = json.loads(match.group(0))
            except json.JSONDecodeError:
                logger.error(
                    f"Failed to parse LLM response as JSON: {response_text[:200]}"
                )
                return {}
        else:
            logger.error(f"No JSON object found in LLM response: {response_text[:200]}")
            return {}

    if not isinstance(match_data, dict):
        logger.error(f"LLM response is not a dict: {type(match_data)}")
        return {}

    # Extract and validate fields
    voice_config_id = match_data.get("voice_config_id")
    confidence = match_data.get("confidence", 0.8)

    # voice_config_id can be None (no match) or a string
    if voice_config_id is not None and not isinstance(voice_config_id, str):
        logger.error(f"voice_config_id is not a valid string or null: {voice_config_id}")
        return {}

    return {
        "voice_config_id": voice_config_id,
        "reasoning": match_data.get("reasoning", ""),
        "confidence": confidence,
    }
